### ISSUE TITLE
Update docker system?

### ISSUE THREAD

**Issue by agilob** [ViViDboarder/docker-rpi-motioneye#1]
Could you please update the system and motion eye please?

**Comment by SmashRocket** [comment]
Would love an update

**Comment by ViViDboarder** [comment]
Hey. I never ended up seeing this due to Github notifications being off.

Current image has the following versions:

* `motion=3.2.12`
* `motioneye=0.36.1`

The base image I'm using is pretty out of date and does not have the recommended version of `motion`.

I could probably manage an update, but it's probably better to just switch to the official image.

https://github.com/ccrisan/motioneye/wiki/Install-in-Docker
